"use client";
import { useState } from "react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { usePortfolio } from "@/hooks/use-portfolio";

export default function PortfolioPage(){
  const portfolio = usePortfolio(); const [address,setAddress]=useState(""); const [status,setStatus]=useState("");
  const trackWallet=async()=>{setStatus("Syncing…");const response=await fetch("/api/wallet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address})});setStatus(response.ok?"Wallet synced":"Add SOLANA_RPC_URL to enable live tracking")};
  return <div className="space-y-6"><PageHeading eyebrow="Wallet intelligence" title="Portfolio" description="Track positions, risk exposure, and realized performance across every connected wallet." action={<div className="flex gap-2"><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Solana wallet address" className="pill w-44 px-3 text-xs sm:w-60"/><Button onClick={trackWallet} disabled={!address}>Track wallet</Button></div>} />{status&&<div className="mono text-[10px] text-[#aab1aa]">{status}</div>}
  <section className="grid gap-3 sm:grid-cols-3">{[["Portfolio value","$42,680.32","+6.8% today"],["Unrealized P&L","+$8,492.18","+24.8% all time"],["Risk exposure","Moderate","2 positions flagged"]].map(([l,v,d])=><div key={l} className="panel p-5"><div className="eyebrow">{l}</div><div className="mt-4 text-2xl font-semibold">{v}</div><div className="mono mt-3 text-[10px] text-[#99c95b]">{d}</div></div>)}</section>
  <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="panel p-5"><div className="flex items-center justify-between"><div className="eyebrow">Responsive performance chart</div><span className="mono text-[10px] text-[#8f968f]">30D</span></div><div className="mt-6 h-56 rounded-xl grid-dots p-5"><div className="flex h-full items-end gap-3">{[65,42,80,32,54,92,72,100,82,107,98,116].map((h,i)=><div key={i} className="flex-1 rounded-t-md bg-[#d8ff3e]" style={{height:`${Math.min(h,100)}%`,opacity:.2+i/18}} />)}</div></div></div><div className="panel p-5"><div className="eyebrow">Tracked positions</div><div className="mt-5 space-y-4">{portfolio.positions.length===0?<><p className="text-xs leading-5 text-[#7c837c]">No manual positions yet. Add a sample to verify local portfolio persistence.</p><Button variant="outline" size="sm" onClick={()=>portfolio.addPosition({symbol:"PEPE",amount:1000000,entryPrice:.00001})}>Add sample position</Button></>:portfolio.positions.map(p=><div key={p.symbol} className="flex items-center border-b border-[#272b27] pb-3"><span className="text-sm">{p.symbol}</span><span className="mono ml-auto text-[10px] text-[#8b928b]">{p.amount.toLocaleString()}</span><button onClick={()=>portfolio.removePosition(p.symbol)} className="ml-3 text-[#717871]">×</button></div>)}</div></div></section></div>
}
